services:
  postgres:
    image: 'postgres:15.4'
    environment:
      - 'POSTGRES_DB=kanban_database'
      - 'POSTGRES_USER=alex_admin'
      - 'POSTGRES_PASSWORD=6LVaw27hRThD'
    ports:
      - '5432:5432'
